name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_contacts: ^1.1.9+2
  google_fonts: ^6.2.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  qr_flutter: ^4.1.0
  screenshot: ^3.0.0
  url_launcher: ^6.3.1
  share_plus: ^11.0.0
  mobile_scanner: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
